import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('🔧 Procedural Machine & Upgrade Designer AI — Running...');

// Load existing machine catalog structure
const catalogPath = path.join(__dirname, '../src/data_exports/machine_catalog.json');
if (!fs.existsSync(catalogPath)) {
  console.error("machine_catalog.json not found! Run generate_machines.ts first.");
  process.exit(1);
}

const machines = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));

// ── Configuration ────────────────────────────────────────────────────────────
const UPGRADE_BRANCHES = ['speed', 'yield', 'durability'];
const BASE_LEVELS = 10;
const MAX_MODULE_SLOTS = 3;

// Mulberry32 PRNG
function mulberry32(a: number) {
  return function() {
    let t = a += 0x6D2B79F5;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }
}
const rng = mulberry32(80085);
function randRange(min: number, max: number): number { return min + rng() * (max - min); }
function randInt(min: number, max: number): number { return Math.floor(randRange(min, max + 1)); }
function randChoice<T>(arr: T[]): T { return arr[Math.floor(rng() * arr.length)]; }

// Attach modules and cosmetics based on tier
const modulePool = {
  planter: ['seed_hopper_ext', 'precision_laser', 'soil_sensor'],
  waterer: ['high_pressure_nozzle', 'mineral_infuser', 'leak_detector'],
  harvester: ['giga_scythe', 'auto_sorter', 'payload_compactor'],
  processor: ['overclock_chip', 'purity_filter', 'heat_sink'],
  drone: ['aero_battery', 'cargo_net', 'ai_pathfinder']
};

const skinStyles = ['neon', 'rusty', 'gold', 'steampunk', 'holo'];

const augmentedMachines = machines.map((m: { 
  tier: number; 
  category: string; 
  machine_id: string;
  name: string;
  base_cost: number;
  production_rate: { crops_per_min: number };
  efficiency_curve: Record<string, number>;
  maintenance_cost_per_hour: number;
  overclockable: boolean;
  overclock_effects?: { speed_multiplier: number; wear_rate_multiplier: number };
  description: string;
}) => {
  // 1. Generate Upgrade Branches
  const upgrades = UPGRADE_BRANCHES.map(branch => {
    // Determine cost curve multiplier based on tier and branch
    // Speed is slightly more expensive
    const baseMult = branch === 'speed' ? 1.25 : (branch === 'yield' ? 1.20 : 1.15);
    const tierCostMod = 1 + (m.tier * 0.05);
    const finalPowerMultiplier = (baseMult * tierCostMod).toFixed(3);
    
    // Determine effect
    let effectTmpl = '';
    if (branch === 'speed') effectTmpl = '+{val}% Production Speed';
    else if (branch === 'yield') effectTmpl = '+{val}% Output Yield';
    else effectTmpl = '-{val}% Wear Rate';
    
    const maxVal = branch === 'speed' ? 100 : (branch === 'yield' ? 50 : 75);

    return {
      branch,
      levels: BASE_LEVELS + (m.tier * 5), // Higher tiers have more upgrade levels
      cost_formula: `base_cost * (${finalPowerMultiplier} ^ level)`,
      effect_per_level: effectTmpl,
      max_effect_val: maxVal
    };
  });

  // 2. Generate Module Slots
  // Tiers 1-2 get 1 slot, Tier 3 gets 2, Tier 4-5 gets 3 slots
  const slotsCount = Math.min(MAX_MODULE_SLOTS, Math.ceil(m.tier / 1.5));
  const validModules = modulePool[m.category as keyof typeof modulePool];
  const attachable_modules = Array.from({length: slotsCount}, () => randChoice(validModules));

  // Deduplicate array
  const unique_modules = Array.from(new Set(attachable_modules));

  // 3. Generate Cosmetic Skins
  const skinCount = randInt(1, 3);
  const cosmetic_skin_ids = Array.from({length: skinCount}, () => `skin_${m.category}_${randChoice(skinStyles)}`);

  return {
    ...m,
    upgrades,
    module_slots: slotsCount,
    compatible_modules: unique_modules,
    cosmetic_skins: Array.from(new Set(cosmetic_skin_ids))
  };
});

// ── Output ───────────────────────────────────────────────────────────────────
const outDir = path.join(__dirname, '../src/data_exports');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
const outPathJSON = path.join(outDir, 'augmented_machines.json');
fs.writeFileSync(outPathJSON, JSON.stringify(augmentedMachines, null, 2));

// Generate TypeScript definitions
const tsContent = `// Auto-generated by economy/generate_machine_upgrades.ts
import type { MachineDef } from './machines';

export interface UpgradeBranch {
  branch: 'speed' | 'yield' | 'durability';
  levels: number;
  costFormula: string;
  effectPerLevel: string;
  maxEffectVal: number;
}

export interface AugmentedMachineDef extends MachineDef {
  upgrades: UpgradeBranch[];
  moduleSlots: number;
  compatibleModules: string[];
  cosmeticSkins: string[];
}

export const AUGMENTED_MACHINES: AugmentedMachineDef[] = ${JSON.stringify(augmentedMachines.map((m: {
  machine_id: string;
  name: string;
  category: string;
  tier: number;
  base_cost: number;
  production_rate: { crops_per_min: number };
  efficiency_curve: Record<string, number>;
  maintenance_cost_per_hour: number;
  overclockable: boolean;
  overclock_effects?: { speed_multiplier: number; wear_rate_multiplier: number };
  description: string;
  upgrades: unknown[];
  module_slots: number;
  compatible_modules: string[];
  cosmetic_skins: string[];
}) => ({
  id: m.machine_id,
  name: m.name,
  category: m.category,
  tier: m.tier,
  baseCost: m.base_cost,
  productionRate: { cropsPerMin: m.production_rate.crops_per_min },
  efficiencyCurve: m.efficiency_curve,
  maintenanceCostPerHour: m.maintenance_cost_per_hour,
  overclockable: m.overclockable,
  overclockEffects: m.overclock_effects ? {
    speedMultiplier: m.overclock_effects.speed_multiplier,
    wearRateMultiplier: m.overclock_effects.wear_rate_multiplier,
  } : undefined,
  description: m.description,
  upgrades: m.upgrades.map((u: {
    branch: 'speed' | 'yield' | 'durability';
    levels: number;
    cost_formula?: string;
    costFormula?: string;
    effect_per_level?: string;
    effectPerLevel?: string;
    max_effect_val?: number;
    maxEffectVal?: number;
  }) => ({
    branch: u.branch,
    levels: u.levels,
    costFormula: u.costFormula || u.cost_formula,
    effectPerLevel: u.effectPerLevel || u.effect_per_level,
    maxEffectVal: u.maxEffectVal || u.max_effect_val
  })),
  moduleSlots: m.module_slots,
  compatibleModules: m.compatible_modules,
  cosmeticSkins: m.cosmetic_skins
})), null, 2).replace(/"([^"]+)":/g, '$1:')};

export const getAugmentedMachine = (id: string): AugmentedMachineDef | undefined => AUGMENTED_MACHINES.find(m => m.id === id);
`;

const tsPath = path.join(__dirname, '../src/data/machine_upgrades.ts');
fs.writeFileSync(tsPath, tsContent);

console.log(`✅ Augmented ${augmentedMachines.length} machines with 3 upgrade branches each, modules, and skins. (${augmentedMachines.length * 3} total upgrade trees)`);
console.log(`📁 JSON: economy/augmented_machines.json`);
console.log(`📁 TS:   src/data/machine_upgrades.ts`);
