import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('👷 Worker & Region Generation AI — Running...');

// ── 1. Worker Generation (40 Types) ─────────────────────────────────────────
// Common to Legendary roles
const workerRoles = [
  "Intern", "Farmhand", "Harvester", "Planter", "Waterer", "Mechanic", 
  "Engineer", "Scientist", "Geneticist", "Manager", "Supervisor", 
  "Logistics expert", "Market Analyst", "Drone Pilot", "Bio-hacker", "Botanist"
];

const tiers = ["Trainee", "Junior", "Senior", "Expert", "Master", "Grandmaster", "Legendary"];

const workers: {
  id: string;
  name: string;
  role: string;
  tier: string;
  hire_cost: number;
  efficiency_bonus: number;
  description: string;
}[] = [];
let workerId = 1;

for (let i = 0; i < 40; i++) {
  const role = workerRoles[i % workerRoles.length];
  const tier = tiers[Math.floor(i / workerRoles.length)] || "Specialist";
  const name = `${tier} ${role}`;
  
  // Exponential cost scaling
  const baseCost = 500 * Math.pow(2.2, Math.floor(i / 5));
  const bonus = 0.05 + (i * 0.02); // 5% to 85% bonus

  workers.push({
    id: `worker_${String(workerId++).padStart(3, '0')}`,
    name,
    role: role.toLowerCase(),
    tier: tier.toLowerCase(),
    hire_cost: Math.floor(baseCost),
    efficiency_bonus: parseFloat(bonus.toFixed(2)),
    description: `A skilled ${name} ready to boost your operations by ${Math.floor(bonus * 100)}%.`
  });
}

// ── 2. Region Generation (12 Regions) ───────────────────────────────────────
const regionNames = [
  "Green Meadows", "Riverlands", "Sunny Plateau", "Dusty Mesa", "Rainy Basin",
  "Frost Peaks", "Volcanic Ridge", "Crystal Valley", "Floating Isles", 
  "Lunar Crater", "Neon Megalopolis", "Agri-Prime Core"
];

const regions: {
  id: string;
  name: string;
  unlock_cost: number;
  multiplier: number;
  weather_affinity: string;
  description: string;
  available_slots: number;
}[] = [];
let regionId = 1;

for (let i = 0; i < 12; i++) {
  const name = regionNames[i];
  // Steep progression curve for unlocks
  const unlockCost = 1000 * Math.pow(10, i);
  
  const weatherAffinities = ["rain", "sun", "wind", "fog", "snow"];
  const dominantWeather = weatherAffinities[i % weatherAffinities.length];

  regions.push({
    id: `region_${String(regionId++).padStart(2, '0')}`,
    name,
    unlock_cost: unlockCost,
    multiplier: 1 + (i * 0.5), // Each region is 50% more productive than the last
    weather_affinity: dominantWeather,
    description: `The ${name}, where the ${dominantWeather} never seems to end. Productivity multiplier: ${1 + (i * 0.5)}x.`,
    available_slots: 10 + (i * 5) // Regions get larger as you progress
  });
}

// ── Output ───────────────────────────────────────────────────────────────────
const outDir = path.join(__dirname, '../src/data_exports');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

fs.writeFileSync(path.join(outDir, 'workers.json'), JSON.stringify(workers, null, 2));
fs.writeFileSync(path.join(outDir, 'regions.json'), JSON.stringify(regions, null, 2));

// TS Export
const tsContent = `// Auto-generated by economy/generate_workers_regions.ts
import workersData from '../data_exports/workers.json';
import regionsData from '../data_exports/regions.json';

export interface WorkerDef {
  id: string;
  name: string;
  role: string;
  tier: string;
  hire_cost: number;
  efficiency_bonus: number;
  description: string;
}

export interface RegionDef {
  id: string;
  name: string;
  unlock_cost: number;
  multiplier: number;
  weather_affinity: string;
  description: string;
  available_slots: number;
}

export const WORKERS: WorkerDef[] = workersData as WorkerDef[];
export const REGIONS: RegionDef[] = regionsData as RegionDef[];

export const getWorker = (id: string) => WORKERS.find(w => w.id === id);
export const getRegion = (id: string) => REGIONS.find(r => r.id === id);
`;

const tsOutDir = path.join(__dirname, '../src/data');
fs.writeFileSync(path.join(tsOutDir, 'world.ts'), tsContent);

console.log(`✅ Generated 40 Workers and 12 Regions successfully.`);
console.log(`📁 JSON: data_exports/workers.json, regions.json`);
console.log(`📁 TS:   src/data/world.ts`);
