import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { CROPS } from '../src/data/crops';
import { MACHINES } from '../src/data/machines';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── Configuration ────────────────────────────────────────────────────────────
const PRESTIGE_DIVISOR = 8000000; // From our game_config.json

interface ProgressionUnlock {
  id: string;
  type: 'crop' | 'machine' | 'region';
  name: string;
  unlock_coins: number;
  tier: number;
}

// ── Region Generation ────────────────────────────────────────────────────────
const REGIONS = [
  { id: 'meadow', name: 'Starter Meadow', base_cost: 0, tier: 1 },
  { id: 'riverlands', name: 'Riverlands', base_cost: 50000, tier: 2 },
  { id: 'desert', name: 'Desert Oasis', base_cost: 250000, tier: 3 },
  { id: 'tundra', name: 'Frozen Tundra', base_cost: 1000000, tier: 4 },
  { id: 'volcanic', name: 'Volcanic Soil', base_cost: 5000000, tier: 5 },
  { id: 'sky', name: 'Sky Farmlands', base_cost: 25000000, tier: 6 },
];

console.log('📈 Progression Tuning AI — Running...');

// ── Generate Unlocks ─────────────────────────────────────────────────────────
const unlocks: ProgressionUnlock[] = [];

// 1. Add all regions
REGIONS.forEach(r => {
  if (r.base_cost > 0) {
    unlocks.push({
      id: r.id,
      type: 'region',
      name: r.name,
      unlock_coins: r.base_cost,
      tier: r.tier,
    });
  }
});

// 2. Add all crops
// Crop unlock cost should be roughly 10x its seed cost, to require some effort before planting it consistently.
CROPS.forEach(c => {
  if (c.unlockTier > 1 || c.seedCost > 15) {
    // Only put uncommon+ or moderately expensive crops as unlocks
    unlocks.push({
      id: c.id,
      type: 'crop',
      name: c.name,
      unlock_coins: Math.max(100, Math.round(c.seedCost * 12.5)),
      tier: c.unlockTier,
    });
  }
});

// 3. Add all machines
// Machine unlock cost: It should be unlocked BEFORE you can easily afford the base cost,
// so you see it in the shop as a goal. Let's make the unlock requirement 0.5x its base cost.
MACHINES.forEach(m => {
  // Tie machine visibility/unlock to 35% of its base cost. So when you are halfway there, it appears.
  const req = Math.max(50, Math.round(m.baseCost * 0.35));
  unlocks.push({
    id: m.id,
    type: 'machine',
    name: m.name,
    unlock_coins: req,
    tier: m.tier,
  });
});

// ── Sort & Validate Monotonic Progression ────────────────────────────────────
unlocks.sort((a, b) => a.unlock_coins - b.unlock_coins);

// Ensure there are no exact duplicates in cost by bumping them slightly
for (let i = 1; i < unlocks.length; i++) {
  if (unlocks[i].unlock_coins <= unlocks[i - 1].unlock_coins) {
    unlocks[i].unlock_coins = unlocks[i - 1].unlock_coins + 10;
  }
}

// ── Format Output ────────────────────────────────────────────────────────────
const unlockTable = unlocks.map(u => ({
  tier: u.tier,
  type: u.type,
  unlock: u.name,
  requirement: `earn ${u.unlock_coins.toLocaleString()} coins`,
  coins_threshold: u.unlock_coins
}));

const prestigeCurve = {
  formula: `prestige_points = sqrt(total_coins / ${PRESTIGE_DIVISOR})`,
  recommended_reset_benefits: [
    "+2% Permanent Machine Efficiency per point",
    "+1% Crop Value per point",
    "Unlocks prestigious cosmetical decorations"
  ]
};

// Next goals for UI (First 20)
const nextGoals = unlocks.slice(0, 20).map(u => `Earn ${u.unlock_coins.toLocaleString()} coins to unlock ${u.type === 'crop' ? 'the ' : ''}${u.name}!`);

const outputJson = {
  unlock_table: unlockTable,
  prestige_curve: prestigeCurve,
  ui_strings: {
    first_20_goals: nextGoals
  }
};

// ── Write Files ──────────────────────────────────────────────────────────────
const outDir = path.join(__dirname, '../src/data_exports');
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

fs.writeFileSync(
  path.join(outDir, 'progression_model.json'),
  JSON.stringify(outputJson, null, 2)
);

// TypeScript string file for the UI 
const tsContent = `// Auto-generated by economy/generate_progression.ts
export interface UnlockGate {
  tier: number;
  type: 'crop' | 'machine' | 'region';
  name: string;
  requirementDesc: string;
  coinsThreshold: number;
}

export const UNLOCKS: UnlockGate[] = ${JSON.stringify(
  unlockTable.map(u => ({
    tier: u.tier,
    type: u.type,
    name: u.unlock,
    requirementDesc: u.requirement,
    coinsThreshold: u.coins_threshold
  })), null, 2
).replace(/"([^"]+)":/g, '$1:')};

export const PRESTIGE_DIVISOR = ${PRESTIGE_DIVISOR};
export const getNextUnlock = (currentCoins: number): UnlockGate | undefined => {
  return UNLOCKS.find(u => u.coinsThreshold > currentCoins);
};
`;

const tsDataOut = path.join(__dirname, '../src/data/progression.ts');
fs.writeFileSync(tsDataOut, tsContent);

console.log(`✅ Generated progression schedule successfully: ${unlocks.length} total milestones.`);
console.log(`📁 JSON: economy/progression_model.json`);
console.log(`📁 TS:   src/data/progression.ts`);
console.log('\n--- First 10 Progression Goals ---');
nextGoals.slice(0, 10).forEach((g, i) => console.log(`${i+1}. ${g}`));
