import type { Metadata, Viewport } from "next";
import "./globals.css";

/* ============================================================================
   ARCHMAGE — root document metadata (V1.1 brand pass).
   ----------------------------------------------------------------------------
   Every icon, preview banner and install target a browser or social crawler
   can ask for is declared here. Files live in public/ and are regenerated by
   one command: `bun run brand` (scripts/build-brand.mjs).

   ASSET_BASE mirrors the GitHub Pages base path (NEXT_PUBLIC_BASE_PATH, set
   by .github/workflows/deploy.yml → /archmage) so the static export serves
   every asset from the right URL. NEXT_PUBLIC_SITE_URL (also set in the
   workflow) makes the Open Graph / Twitter card images absolute for crawlers.
   ============================================================================ */

const ASSET_BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

const DESCRIPTION =
  "A pure arcade roguelike. Thirteen dark arts, seventy-eight resonances, five shuffled tyrants, adaptive procedural music — and zero interruptions. Weave spells fast enough and the rift sings your name.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Archmage — Rift Survivor",
  description: DESCRIPTION,
  applicationName: "Archmage",
  keywords: ["Archmage", "roguelike", "roguelite", "magic", "canvas game", "wave survival", "spell weaving", "browser game", "Hades-like", "Vampire Survivors-like"],
  icons: {
    icon: [
      { url: `${ASSET_BASE}/favicon.svg`, type: "image/svg+xml" },
      { url: `${ASSET_BASE}/favicon-32x32.png`, sizes: "32x32", type: "image/png" },
      { url: `${ASSET_BASE}/favicon-16x16.png`, sizes: "16x16", type: "image/png" },
    ],
    shortcut: [{ url: `${ASSET_BASE}/favicon.ico` }],
    apple: [{ url: `${ASSET_BASE}/apple-touch-icon.png`, sizes: "180x180" }],
  },
  manifest: `${ASSET_BASE}/site.webmanifest`,
  openGraph: {
    type: "website",
    title: "Archmage — Rift Survivor",
    description: DESCRIPTION,
    siteName: "Archmage — Rift Survivor",
    images: [{ url: `${ASSET_BASE}/art/og-image.png`, width: 1200, height: 630, alt: "Archmage — an archmage facing a gold-and-violet rift portal" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Archmage — Rift Survivor",
    description: DESCRIPTION,
    images: [`${ASSET_BASE}/art/twitter-card.png`],
  },
  appleWebApp: {
    capable: true,
    title: "Archmage",
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0b0716",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font -- App Router root layout (not a pages-router page); runtime link avoids next/font build-time network dependency */}
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700;800;900&family=Alegreya+Sans:ital,wght@0,400;0,500;0,700;0,800;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased" style={{ background: "#0b0716", margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
