export const GAME_CONFIG = {
  REGION_BASE: 5,
  CROP_GROWTH_BASE: 1.2,
  CROP_VALUE_BASE: 1.8,
  MACHINE_COST_SCALING: 1.15,
  WORKER_COST_SCALING: 1.5,
  WORKER_BONUS_SCALING: 1.25,
  BOSS_HP_BASE: 2500,
  BOSS_HP_SCALING: 25,
  OVERCLOCK_MULTIPLIER: 5,
  OVERCLOCK_MAINTENANCE: 3,
  PRESTIGE_LOG_BASE: 10,
  PRESTIGE_BONUS_PER_POINT: 0.05,
} as const;
