// AUTO-GENERATED by economy/generate_crops.ts (CropGen AI)
// Edit economy/generate_crops.ts to change crops, then re-run.
// All values validated by CropGen AI KPI checks.

export interface Crop {
  id: string;
  name: string;
  emoji: string;
  growthTime: number;   // seconds
  yield: number;
  baseValue: number;
  seedCost: number;
  soilType: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  growthBucket: 'early' | 'mid' | 'late';
  weatherBonus: number; // multiplier applied during weather affinity events
  weatherAffinity: string[];
  machineSynergy: string[];
  unlockTier: number;
  unlockRegion: string;
  description: string;
}

export const CROPS: Crop[] = [
  {
    "id": "crop_001",
    "name": "Wheat",
    "emoji": "🌾",
    "growthTime": 30,
    "yield": 4,
    "baseValue": 11,
    "seedCost": 6,
    "soilType": "meadow",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny",
      "rainstorm"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "The backbone of any farm. Grows fast, sells reliably."
  },
  {
    "id": "crop_002",
    "name": "Corn",
    "emoji": "🌽",
    "growthTime": 45,
    "yield": 3,
    "baseValue": 21,
    "seedCost": 11,
    "soilType": "meadow",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Warm-weather staple with consistent yields."
  },
  {
    "id": "crop_003",
    "name": "Potato",
    "emoji": "🥔",
    "growthTime": 60,
    "yield": 5,
    "baseValue": 16,
    "seedCost": 8,
    "soilType": "highlands",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_harvester",
      "processing_unit"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Rugged and reliable — it grows almost anywhere."
  },
  {
    "id": "crop_004",
    "name": "Carrot",
    "emoji": "🥕",
    "growthTime": 40,
    "yield": 4,
    "baseValue": 14,
    "seedCost": 7,
    "soilType": "meadow",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny",
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "A crunchy favourite. Perfect for market days."
  },
  {
    "id": "crop_005",
    "name": "Tomato",
    "emoji": "🍅",
    "growthTime": 50,
    "yield": 3,
    "baseValue": 23,
    "seedCost": 12,
    "soilType": "riverlands",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Sun-kissed and plump, ready for the saucemaker."
  },
  {
    "id": "crop_006",
    "name": "Lettuce",
    "emoji": "🥬",
    "growthTime": 20,
    "yield": 3,
    "baseValue": 10,
    "seedCost": 5,
    "soilType": "meadow",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Fast-growing leafy green. The salad king."
  },
  {
    "id": "crop_007",
    "name": "Radish",
    "emoji": "🌰",
    "growthTime": 10,
    "yield": 2,
    "baseValue": 8,
    "seedCost": 4,
    "soilType": "highlands",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "The fastest crop on the farm. Quick coins, quick satisfaction."
  },
  {
    "id": "crop_008",
    "name": "Pea",
    "emoji": "🫛",
    "growthTime": 35,
    "yield": 4,
    "baseValue": 12,
    "seedCost": 6,
    "soilType": "meadow",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny",
      "rainstorm"
    ],
    "machineSynergy": [
      "seed_sorter",
      "grain_mill"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Tiny pods, big harvests. Great for seed cycling."
  },
  {
    "id": "crop_009",
    "name": "Bean",
    "emoji": "🫘",
    "growthTime": 55,
    "yield": 5,
    "baseValue": 15,
    "seedCost": 8,
    "soilType": "riverlands",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "seed_sorter",
      "grain_mill"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "A protein powerhouse. Beans go into everything."
  },
  {
    "id": "crop_010",
    "name": "Cabbage",
    "emoji": "🥦",
    "growthTime": 70,
    "yield": 4,
    "baseValue": 23,
    "seedCost": 12,
    "soilType": "highlands",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Dense and dependable. Favoured in cold highland plots."
  },
  {
    "id": "crop_011",
    "name": "Spinach",
    "emoji": "🍃",
    "growthTime": 25,
    "yield": 3,
    "baseValue": 12,
    "seedCost": 6,
    "soilType": "meadow",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Iron-rich and fast-growing. Farmers love the turnaround."
  },
  {
    "id": "crop_012",
    "name": "Garlic",
    "emoji": "🧄",
    "growthTime": 80,
    "yield": 3,
    "baseValue": 34,
    "seedCost": 17,
    "soilType": "highlands",
    "rarity": "common",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 1,
    "unlockRegion": "meadow",
    "description": "Pungent perfection. Doubles as pest control."
  },
  {
    "id": "crop_013",
    "name": "Soybean",
    "emoji": "🌱",
    "growthTime": 65,
    "yield": 5,
    "baseValue": 27,
    "seedCost": 14,
    "soilType": "meadow",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "seed_sorter",
      "grain_mill"
    ],
    "unlockTier": 2,
    "unlockRegion": "meadow",
    "description": "The plant that feeds the world — and your machines."
  },
  {
    "id": "crop_014",
    "name": "Sunflower",
    "emoji": "🌻",
    "growthTime": 70,
    "yield": 4,
    "baseValue": 37,
    "seedCost": 19,
    "soilType": "meadow",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "cold_storage"
    ],
    "unlockTier": 2,
    "unlockRegion": "meadow",
    "description": "Tall, golden, photosynthetically aggressive."
  },
  {
    "id": "crop_015",
    "name": "Pumpkin",
    "emoji": "🎃",
    "growthTime": 85,
    "yield": 4,
    "baseValue": 44,
    "seedCost": 22,
    "soilType": "highlands",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "fertile"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 2,
    "unlockRegion": "highlands",
    "description": "Seasonal superstar. Farmers swear by autumn harvests."
  },
  {
    "id": "crop_016",
    "name": "Ginger",
    "emoji": "🫚",
    "growthTime": 90,
    "yield": 3,
    "baseValue": 61,
    "seedCost": 31,
    "soilType": "riverlands",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 2,
    "unlockRegion": "riverlands",
    "description": "A fiery root. Prized in markets and medicine halls."
  },
  {
    "id": "crop_017",
    "name": "Pepper",
    "emoji": "🌶",
    "growthTime": 75,
    "yield": 3,
    "baseValue": 52,
    "seedCost": 26,
    "soilType": "meadow",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 2,
    "unlockRegion": "meadow",
    "description": "Bold heat in small packages. The spice trade starts here."
  },
  {
    "id": "crop_018",
    "name": "Onion",
    "emoji": "🧅",
    "growthTime": 60,
    "yield": 4,
    "baseValue": 32,
    "seedCost": 16,
    "soilType": "highlands",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 2,
    "unlockRegion": "highlands",
    "description": "Brings tears in the field, cheers at the market."
  },
  {
    "id": "crop_019",
    "name": "Basil",
    "emoji": "🌿",
    "growthTime": 35,
    "yield": 3,
    "baseValue": 26,
    "seedCost": 13,
    "soilType": "riverlands",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 2,
    "unlockRegion": "riverlands",
    "description": "Fragrant gold. Worth triple the coin when extracted."
  },
  {
    "id": "crop_020",
    "name": "Mint",
    "emoji": "🍀",
    "growthTime": 30,
    "yield": 4,
    "baseValue": 17,
    "seedCost": 9,
    "soilType": "riverlands",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 2,
    "unlockRegion": "riverlands",
    "description": "Cool and fast-spreading. Essential for the extract line."
  },
  {
    "id": "crop_021",
    "name": "Chamomile",
    "emoji": "🌼",
    "growthTime": 55,
    "yield": 3,
    "baseValue": 39,
    "seedCost": 20,
    "soilType": "meadow",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "cold_storage"
    ],
    "unlockTier": 2,
    "unlockRegion": "meadow",
    "description": "Calming and profitable. Florists and apothecaries compete."
  },
  {
    "id": "crop_022",
    "name": "Kale",
    "emoji": "🥬",
    "growthTime": 45,
    "yield": 5,
    "baseValue": 20,
    "seedCost": 10,
    "soilType": "highlands",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 2,
    "unlockRegion": "highlands",
    "description": "The superfood of choice. Cold-hardy and nutrient-dense."
  },
  {
    "id": "crop_023",
    "name": "Lentil",
    "emoji": "🫘",
    "growthTime": 50,
    "yield": 4,
    "baseValue": 27,
    "seedCost": 14,
    "soilType": "meadow",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "seed_sorter",
      "grain_mill"
    ],
    "unlockTier": 2,
    "unlockRegion": "meadow",
    "description": "Ancient and humble. Lentils power civilisations."
  },
  {
    "id": "crop_024",
    "name": "Fennel",
    "emoji": "🌾",
    "growthTime": 65,
    "yield": 3,
    "baseValue": 46,
    "seedCost": 23,
    "soilType": "riverlands",
    "rarity": "uncommon",
    "growthBucket": "early",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 2,
    "unlockRegion": "riverlands",
    "description": "Anise-sweet and elegant. Cooks pay premium."
  },
  {
    "id": "crop_025",
    "name": "Rice",
    "emoji": "🌾",
    "growthTime": 90,
    "yield": 6,
    "baseValue": 31,
    "seedCost": 16,
    "soilType": "riverlands",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 2,
    "unlockRegion": "riverlands",
    "description": "Wetland wonder. Feeds half the world's appetite."
  },
  {
    "id": "crop_026",
    "name": "Sugarcane",
    "emoji": "🎋",
    "growthTime": 120,
    "yield": 5,
    "baseValue": 48,
    "seedCost": 24,
    "soilType": "tropical",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "mega_harvester",
      "ai_farm_mgr",
      "processing_unit"
    ],
    "unlockTier": 2,
    "unlockRegion": "tropical",
    "description": "Sweet gold. Refined into sugar, ethanol, and profit."
  },
  {
    "id": "crop_027",
    "name": "Oats",
    "emoji": "🌾",
    "growthTime": 100,
    "yield": 5,
    "baseValue": 40,
    "seedCost": 20,
    "soilType": "highlands",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 2,
    "unlockRegion": "highlands",
    "description": "Hardy highland grain. Cold-weather masterpiece."
  },
  {
    "id": "crop_028",
    "name": "Buckwheat",
    "emoji": "🌸",
    "growthTime": 110,
    "yield": 4,
    "baseValue": 55,
    "seedCost": 28,
    "soilType": "highlands",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 2,
    "unlockRegion": "highlands",
    "description": "Gluten-free and fast. High upland crop demand."
  },
  {
    "id": "crop_029",
    "name": "Barley",
    "emoji": "🌾",
    "growthTime": 130,
    "yield": 5,
    "baseValue": 51,
    "seedCost": 26,
    "soilType": "meadow",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny",
      "rainstorm"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 2,
    "unlockRegion": "meadow",
    "description": "The brewer's darling. Barley leads all fermentation chains."
  },
  {
    "id": "crop_030",
    "name": "Lavender",
    "emoji": "💜",
    "growthTime": 150,
    "yield": 3,
    "baseValue": 97,
    "seedCost": 49,
    "soilType": "highlands",
    "rarity": "uncommon",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "cold_storage"
    ],
    "unlockTier": 2,
    "unlockRegion": "highlands",
    "description": "Aromatherapy in plant form. Extract prices are extraordinary."
  },
  {
    "id": "crop_031",
    "name": "Grape",
    "emoji": "🍇",
    "growthTime": 200,
    "yield": 5,
    "baseValue": 141,
    "seedCost": 71,
    "soilType": "highlands",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "juice_press",
      "auto_harvester"
    ],
    "unlockTier": 3,
    "unlockRegion": "highlands",
    "description": "The vintage begins here. Four processing tiers await."
  },
  {
    "id": "crop_032",
    "name": "Strawberry",
    "emoji": "🍓",
    "growthTime": 180,
    "yield": 4,
    "baseValue": 161,
    "seedCost": 81,
    "soilType": "meadow",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "juice_press",
      "auto_harvester"
    ],
    "unlockTier": 3,
    "unlockRegion": "meadow",
    "description": "Delicate and fleeting. Peak-season prices are the highest."
  },
  {
    "id": "crop_033",
    "name": "Blueberry",
    "emoji": "🫐",
    "growthTime": 240,
    "yield": 4,
    "baseValue": 208,
    "seedCost": 104,
    "soilType": "highlands",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "juice_press",
      "auto_harvester"
    ],
    "unlockTier": 3,
    "unlockRegion": "highlands",
    "description": "Antioxidant powerhouse. Export demand always strong."
  },
  {
    "id": "crop_034",
    "name": "Coffee",
    "emoji": "☕",
    "growthTime": 300,
    "yield": 3,
    "baseValue": 339,
    "seedCost": 170,
    "soilType": "tropical",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "mega_harvester",
      "ai_farm_mgr",
      "processing_unit"
    ],
    "unlockTier": 3,
    "unlockRegion": "tropical",
    "description": "The world's favourite stimulant. Roast it for 3x returns."
  },
  {
    "id": "crop_035",
    "name": "Tea",
    "emoji": "🍵",
    "growthTime": 250,
    "yield": 4,
    "baseValue": 216,
    "seedCost": 108,
    "soilType": "highlands",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 3,
    "unlockRegion": "highlands",
    "description": "Calming leaves with obsessive global demand."
  },
  {
    "id": "crop_036",
    "name": "Vanilla",
    "emoji": "🌸",
    "growthTime": 400,
    "yield": 2,
    "baseValue": 659,
    "seedCost": 330,
    "soilType": "tropical",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 3,
    "unlockRegion": "tropical",
    "description": "The world's second most expensive spice. Extract is worth fortunes."
  },
  {
    "id": "crop_037",
    "name": "Mango",
    "emoji": "🥭",
    "growthTime": 220,
    "yield": 4,
    "baseValue": 192,
    "seedCost": 96,
    "soilType": "tropical",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "juice_press"
    ],
    "unlockTier": 3,
    "unlockRegion": "tropical",
    "description": "King of tropical fruits. Juice revenue is exceptional."
  },
  {
    "id": "crop_038",
    "name": "Pineapple",
    "emoji": "🍍",
    "growthTime": 280,
    "yield": 3,
    "baseValue": 319,
    "seedCost": 160,
    "soilType": "tropical",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "juice_press"
    ],
    "unlockTier": 3,
    "unlockRegion": "tropical",
    "description": "Spiky exterior, sweet reward. Canning adds major value."
  },
  {
    "id": "crop_039",
    "name": "Papaya",
    "emoji": "🪔",
    "growthTime": 260,
    "yield": 4,
    "baseValue": 224,
    "seedCost": 112,
    "soilType": "tropical",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "juice_press"
    ],
    "unlockTier": 3,
    "unlockRegion": "tropical",
    "description": "Enzymes in every bite. Prized by pharmaceutical buyers."
  },
  {
    "id": "crop_040",
    "name": "Cacao",
    "emoji": "🍫",
    "growthTime": 350,
    "yield": 3,
    "baseValue": 390,
    "seedCost": 195,
    "soilType": "tropical",
    "rarity": "rare",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "mega_harvester",
      "ai_farm_mgr",
      "processing_unit"
    ],
    "unlockTier": 3,
    "unlockRegion": "tropical",
    "description": "The raw material of chocolate empires. Four stages of bliss."
  },
  {
    "id": "crop_041",
    "name": "Dragon Fruit",
    "emoji": "🐉",
    "growthTime": 450,
    "yield": 3,
    "baseValue": 1140,
    "seedCost": 570,
    "soilType": "desert",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "mega_harvester"
    ],
    "unlockTier": 4,
    "unlockRegion": "arid",
    "description": "Otherworldly in appearance, extraordinary in market value."
  },
  {
    "id": "crop_042",
    "name": "Saffron",
    "emoji": "🌷",
    "growthTime": 500,
    "yield": 1,
    "baseValue": 1880,
    "seedCost": 940,
    "soilType": "highlands",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "cold_storage"
    ],
    "unlockTier": 4,
    "unlockRegion": "highlands",
    "description": "The world's most expensive spice by weight. Rarity is the point."
  },
  {
    "id": "crop_043",
    "name": "Black Truffle",
    "emoji": "🍄",
    "growthTime": 480,
    "yield": 2,
    "baseValue": 1812,
    "seedCost": 906,
    "soilType": "highlands",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "cold_storage",
      "processing_unit"
    ],
    "unlockTier": 4,
    "unlockRegion": "highlands",
    "description": "Found underground, sold in high-end restaurants worldwide."
  },
  {
    "id": "crop_044",
    "name": "Avocado",
    "emoji": "🥑",
    "growthTime": 420,
    "yield": 3,
    "baseValue": 1071,
    "seedCost": 536,
    "soilType": "tropical",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "juice_press"
    ],
    "unlockTier": 4,
    "unlockRegion": "tropical",
    "description": "The millennial crop. Demand never wavers."
  },
  {
    "id": "crop_045",
    "name": "Artichoke",
    "emoji": "🌿",
    "growthTime": 360,
    "yield": 2,
    "baseValue": 1399,
    "seedCost": 700,
    "soilType": "highlands",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "fertile"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 4,
    "unlockRegion": "highlands",
    "description": "Architectural beauty with a gourmet price tag."
  },
  {
    "id": "crop_046",
    "name": "Quinoa",
    "emoji": "🌾",
    "growthTime": 390,
    "yield": 4,
    "baseValue": 752,
    "seedCost": 376,
    "soilType": "highlands",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "grain_mill",
      "auto_harvester"
    ],
    "unlockTier": 4,
    "unlockRegion": "highlands",
    "description": "The super-grain of lost civilisations. Premium health-food pricing."
  },
  {
    "id": "crop_047",
    "name": "Chia",
    "emoji": "🌱",
    "growthTime": 340,
    "yield": 5,
    "baseValue": 531,
    "seedCost": 266,
    "soilType": "desert",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "seed_sorter",
      "grain_mill"
    ],
    "unlockTier": 4,
    "unlockRegion": "arid",
    "description": "Tiny seeds, enormous nutritional value. Global export potential."
  },
  {
    "id": "crop_048",
    "name": "Tahitian Lime",
    "emoji": "🍋",
    "growthTime": 380,
    "yield": 3,
    "baseValue": 979,
    "seedCost": 490,
    "soilType": "tropical",
    "rarity": "epic",
    "growthBucket": "mid",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "rainstorm",
      "sunny"
    ],
    "machineSynergy": [
      "juice_press",
      "auto_harvester"
    ],
    "unlockTier": 4,
    "unlockRegion": "tropical",
    "description": "Citrus royalty. The extract is used in luxury beverage lines."
  },
  {
    "id": "crop_049",
    "name": "Wasabi Root",
    "emoji": "🟢",
    "growthTime": 900,
    "yield": 2,
    "baseValue": 3191,
    "seedCost": 1596,
    "soilType": "riverlands",
    "rarity": "epic",
    "growthBucket": "late",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "rainstorm",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "roaster"
    ],
    "unlockTier": 4,
    "unlockRegion": "riverlands",
    "description": "Grows only in cold stream beds. Authentic demand keeps prices elite."
  },
  {
    "id": "crop_050",
    "name": "Blue Oyster Mushroom",
    "emoji": "🍄",
    "growthTime": 720,
    "yield": 4,
    "baseValue": 1305,
    "seedCost": 653,
    "soilType": "riverlands",
    "rarity": "epic",
    "growthBucket": "late",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "cold_storage",
      "processing_unit"
    ],
    "unlockTier": 4,
    "unlockRegion": "riverlands",
    "description": "Medical-grade mycelium. Extract commands pharmaceutical rates."
  },
  {
    "id": "crop_051",
    "name": "White Truffle",
    "emoji": "✨",
    "growthTime": 3600,
    "yield": 1,
    "baseValue": 31747,
    "seedCost": 15874,
    "soilType": "highlands",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "fertile"
    ],
    "machineSynergy": [
      "cold_storage",
      "processing_unit"
    ],
    "unlockTier": 5,
    "unlockRegion": "highlands",
    "description": "The jewel of gastronomy. A single harvest is worth a machine."
  },
  {
    "id": "crop_052",
    "name": "Kopi Luwak",
    "emoji": "☕",
    "growthTime": 2400,
    "yield": 1,
    "baseValue": 22040,
    "seedCost": 11020,
    "soilType": "tropical",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "mega_harvester",
      "ai_farm_mgr",
      "processing_unit"
    ],
    "unlockTier": 5,
    "unlockRegion": "tropical",
    "description": "The world's rarest coffee. A cup sells for $80. You grow the beans."
  },
  {
    "id": "crop_053",
    "name": "Ghost Pepper",
    "emoji": "🔥",
    "growthTime": 1800,
    "yield": 2,
    "baseValue": 17013,
    "seedCost": 8507,
    "soilType": "desert",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "auto_planter",
      "drip_irrigation"
    ],
    "unlockTier": 5,
    "unlockRegion": "arid",
    "description": "Record-breaking Scoville rating. Pharmaceutical and food-tech buyers compete."
  },
  {
    "id": "crop_054",
    "name": "Sea Grape",
    "emoji": "🌊",
    "growthTime": 2700,
    "yield": 2,
    "baseValue": 24505,
    "seedCost": 12253,
    "soilType": "coastal",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "rainstorm",
      "sunny"
    ],
    "machineSynergy": [
      "juice_press",
      "auto_harvester"
    ],
    "unlockTier": 5,
    "unlockRegion": "coastal",
    "description": "Rare coastal delicacy. Only grows in salt-kissed soils near water."
  },
  {
    "id": "crop_055",
    "name": "Argan Blossom",
    "emoji": "🌺",
    "growthTime": 2100,
    "yield": 1,
    "baseValue": 19545,
    "seedCost": 9773,
    "soilType": "desert",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "cold_storage"
    ],
    "unlockTier": 5,
    "unlockRegion": "arid",
    "description": "The desert's treasure. Cold-pressed oil trades at extreme premiums."
  },
  {
    "id": "crop_056",
    "name": "Matsutake",
    "emoji": "🍄",
    "growthTime": 4200,
    "yield": 1,
    "baseValue": 36472,
    "seedCost": 18236,
    "soilType": "highlands",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.2,
    "weatherAffinity": [
      "rainstorm"
    ],
    "machineSynergy": [
      "cold_storage",
      "processing_unit"
    ],
    "unlockTier": 5,
    "unlockRegion": "highlands",
    "description": "Japan's sacred mushroom. Gifted to emperors. Now sold to your buyers."
  },
  {
    "id": "crop_057",
    "name": "Manuka Flower",
    "emoji": "🌸",
    "growthTime": 3000,
    "yield": 2,
    "baseValue": 26943,
    "seedCost": 13472,
    "soilType": "coastal",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "sunny",
      "fertile"
    ],
    "machineSynergy": [
      "drip_irrigation",
      "cold_storage"
    ],
    "unlockTier": 5,
    "unlockRegion": "coastal",
    "description": "The source of Manuka honey. Medical-grade antibacterial properties."
  },
  {
    "id": "crop_058",
    "name": "Oud Resin",
    "emoji": "🪵",
    "growthTime": 5400,
    "yield": 1,
    "baseValue": 45728,
    "seedCost": 22864,
    "soilType": "tropical",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.3,
    "weatherAffinity": [
      "sunny"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "mega_harvester"
    ],
    "unlockTier": 5,
    "unlockRegion": "tropical",
    "description": "Liquid gold from agarwood trees. A kilogram trades for $10,000."
  },
  {
    "id": "crop_059",
    "name": "Lunar Melon",
    "emoji": "🌙",
    "growthTime": 7000,
    "yield": 2,
    "baseValue": 57759,
    "seedCost": 28880,
    "soilType": "highlands",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "fertile"
    ],
    "machineSynergy": [
      "hydroponic_bay",
      "mega_harvester"
    ],
    "unlockTier": 5,
    "unlockRegion": "highlands",
    "description": "A mythic heirloom variety. Said to only fruit under full-moon cycles."
  },
  {
    "id": "crop_060",
    "name": "Aurora Cacao",
    "emoji": "🌌",
    "growthTime": 6500,
    "yield": 1,
    "baseValue": 54032,
    "seedCost": 27016,
    "soilType": "tropical",
    "rarity": "legendary",
    "growthBucket": "late",
    "weatherBonus": 1.5,
    "weatherAffinity": [
      "fertile",
      "sunny"
    ],
    "machineSynergy": [
      "mega_harvester",
      "ai_farm_mgr",
      "processing_unit"
    ],
    "unlockTier": 5,
    "unlockRegion": "tropical",
    "description": "A genetic marvel of cacao genetics. Chocolate houses pay fortunes for it."
  }
];
