// Auto-generated by economy/generate_machine_upgrades.ts
import type { MachineDef } from './machines';

export interface UpgradeBranch {
  branch: 'speed' | 'yield' | 'durability';
  levels: number;
  costFormula: string;
  effectPerLevel: string;
  maxEffectVal: number;
}

export interface AugmentedMachineDef extends MachineDef {
  upgrades: UpgradeBranch[];
  moduleSlots: number;
  compatibleModules: string[];
  cosmeticSkins: string[];
}

export const AUGMENTED_MACHINES: AugmentedMachineDef[] = [
  {
    id: "mach_plan_1_00",
    name: "Root-Bot Mk 1",
    category: "planter",
    tier: 1,
    baseCost: 13,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.7
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.6,
      wearRateMultiplier: 2.3
    },
    description: "Automates seed sowing. Tier 1 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "precision_laser"
    ],
    cosmeticSkins: [
      "skin_planter_gold",
      "skin_planter_rusty"
    ]
  },
  {
    id: "mach_plan_1_01",
    name: "Terra-Core 100",
    category: "planter",
    tier: 1,
    baseCost: 14,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.9,
      level_10: 3
    },
    maintenanceCostPerHour: 1,
    overclockable: false,
    description: "Automates seed sowing. Tier 1 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "seed_hopper_ext"
    ],
    cosmeticSkins: [
      "skin_planter_gold",
      "skin_planter_rusty"
    ]
  },
  {
    id: "mach_plan_1_02",
    name: "Furrow-Matic 100",
    category: "planter",
    tier: 1,
    baseCost: 14,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.7
    },
    maintenanceCostPerHour: 1,
    overclockable: false,
    description: "Automates seed sowing. Tier 1 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "soil_sensor"
    ],
    cosmeticSkins: [
      "skin_planter_holo",
      "skin_planter_rusty"
    ]
  },
  {
    id: "mach_plan_1_03",
    name: "Root-Tech v1.0",
    category: "planter",
    tier: 1,
    baseCost: 35,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.9,
      level_10: 2.5
    },
    maintenanceCostPerHour: 1,
    overclockable: false,
    description: "Automates seed sowing. Tier 1 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "precision_laser"
    ],
    cosmeticSkins: [
      "skin_planter_rusty",
      "skin_planter_neon"
    ]
  },
  {
    id: "mach_plan_1_04",
    name: "Soil-Bot v1.0",
    category: "planter",
    tier: 1,
    baseCost: 17,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.5
    },
    maintenanceCostPerHour: 1,
    overclockable: false,
    description: "Automates seed sowing. Tier 1 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "precision_laser"
    ],
    cosmeticSkins: [
      "skin_planter_steampunk",
      "skin_planter_rusty",
      "skin_planter_neon"
    ]
  },
  {
    id: "mach_plan_1_05",
    name: "Seed-Max 1000",
    category: "planter",
    tier: 1,
    baseCost: 26,
    productionRate: {
      cropsPerMin: 3
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.2
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.3,
      wearRateMultiplier: 1.7
    },
    description: "Automates seed sowing. Tier 1 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "seed_hopper_ext"
    ],
    cosmeticSkins: [
      "skin_planter_rusty",
      "skin_planter_steampunk"
    ]
  },
  {
    id: "mach_plan_1_06",
    name: "Seed-Matic 1000",
    category: "planter",
    tier: 1,
    baseCost: 15,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 2.9
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.7,
      wearRateMultiplier: 2.6
    },
    description: "Automates seed sowing. Tier 1 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "precision_laser"
    ],
    cosmeticSkins: [
      "skin_planter_gold",
      "skin_planter_neon",
      "skin_planter_steampunk"
    ]
  },
  {
    id: "mach_plan_1_07",
    name: "Seed-Forge Mk 1",
    category: "planter",
    tier: 1,
    baseCost: 43,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 3.1
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.7,
      wearRateMultiplier: 2.7
    },
    description: "Automates seed sowing. Tier 1 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "soil_sensor"
    ],
    cosmeticSkins: [
      "skin_planter_neon",
      "skin_planter_steampunk"
    ]
  },
  {
    id: "mach_plan_1_08",
    name: "Soil-Tron v1.0",
    category: "planter",
    tier: 1,
    baseCost: 19,
    productionRate: {
      cropsPerMin: 2
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.6
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 2,
      wearRateMultiplier: 3.2
    },
    description: "Automates seed sowing. Tier 1 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "seed_hopper_ext"
    ],
    cosmeticSkins: [
      "skin_planter_neon",
      "skin_planter_holo"
    ]
  },
  {
    id: "mach_plan_1_09",
    name: "Terra-Tron 100",
    category: "planter",
    tier: 1,
    baseCost: 34,
    productionRate: {
      cropsPerMin: 3
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.9
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.4,
      wearRateMultiplier: 1.8
    },
    description: "Automates seed sowing. Tier 1 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 15,
        costFormula: "base_cost * (1.313 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 15,
        costFormula: "base_cost * (1.260 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 15,
        costFormula: "base_cost * (1.208 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 1,
    compatibleModules: [
      "precision_laser"
    ],
    cosmeticSkins: [
      "skin_planter_gold"
    ]
  },
  {
    id: "mach_wate_2_00",
    name: "Irrig-Tron X2",
    category: "waterer",
    tier: 2,
    baseCost: 270,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.6
    },
    maintenanceCostPerHour: 6,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.6,
      wearRateMultiplier: 2.6
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "leak_detector"
    ],
    cosmeticSkins: [
      "skin_waterer_neon",
      "skin_waterer_gold"
    ]
  },
  {
    id: "mach_wate_2_01",
    name: "Mist-Forge 2000",
    category: "waterer",
    tier: 2,
    baseCost: 76,
    productionRate: {
      cropsPerMin: 4
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2.5
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.7,
      wearRateMultiplier: 2.6
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "high_pressure_nozzle"
    ],
    cosmeticSkins: [
      "skin_waterer_neon",
      "skin_waterer_rusty",
      "skin_waterer_holo"
    ]
  },
  {
    id: "mach_wate_2_02",
    name: "Irrig-Sync v2.0",
    category: "waterer",
    tier: 2,
    baseCost: 230,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2.3
    },
    maintenanceCostPerHour: 6,
    overclockable: false,
    description: "Maintains optimal soil moisture. Tier 2 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "mineral_infuser",
      "high_pressure_nozzle"
    ],
    cosmeticSkins: [
      "skin_waterer_holo"
    ]
  },
  {
    id: "mach_wate_2_03",
    name: "Aqua-Max X2",
    category: "waterer",
    tier: 2,
    baseCost: 430,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2.3
    },
    maintenanceCostPerHour: 8,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.9,
      wearRateMultiplier: 2.7
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "leak_detector",
      "mineral_infuser"
    ],
    cosmeticSkins: [
      "skin_waterer_steampunk",
      "skin_waterer_holo",
      "skin_waterer_rusty"
    ]
  },
  {
    id: "mach_wate_2_04",
    name: "Irrig-Max Pro",
    category: "waterer",
    tier: 2,
    baseCost: 340,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.9,
      level_10: 2.5
    },
    maintenanceCostPerHour: 4,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.5,
      wearRateMultiplier: 1.8
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "mineral_infuser",
      "leak_detector"
    ],
    cosmeticSkins: [
      "skin_waterer_gold",
      "skin_waterer_holo"
    ]
  },
  {
    id: "mach_wate_2_05",
    name: "Flow-Matic 200",
    category: "waterer",
    tier: 2,
    baseCost: 97,
    productionRate: {
      cropsPerMin: 4
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.7
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.5,
      wearRateMultiplier: 2.5
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "mineral_infuser",
      "high_pressure_nozzle"
    ],
    cosmeticSkins: [
      "skin_waterer_steampunk"
    ]
  },
  {
    id: "mach_wate_2_06",
    name: "Flow-Matic 2000",
    category: "waterer",
    tier: 2,
    baseCost: 390,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.4,
      level_10: 2.4
    },
    maintenanceCostPerHour: 9,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.7,
      wearRateMultiplier: 2.7
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "high_pressure_nozzle",
      "leak_detector"
    ],
    cosmeticSkins: [
      "skin_waterer_neon",
      "skin_waterer_steampunk",
      "skin_waterer_holo"
    ]
  },
  {
    id: "mach_wate_2_07",
    name: "Aqua-Sync 2000",
    category: "waterer",
    tier: 2,
    baseCost: 58,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.5
    },
    maintenanceCostPerHour: 1,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.6,
      wearRateMultiplier: 2.9
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "mineral_infuser",
      "high_pressure_nozzle"
    ],
    cosmeticSkins: [
      "skin_waterer_holo"
    ]
  },
  {
    id: "mach_wate_2_08",
    name: "Hydro-Core Pro",
    category: "waterer",
    tier: 2,
    baseCost: 250,
    productionRate: {
      cropsPerMin: 5
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.2
    },
    maintenanceCostPerHour: 6,
    overclockable: false,
    description: "Maintains optimal soil moisture. Tier 2 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "high_pressure_nozzle"
    ],
    cosmeticSkins: [
      "skin_waterer_steampunk"
    ]
  },
  {
    id: "mach_wate_2_09",
    name: "Irrig-Max Mk 2",
    category: "waterer",
    tier: 2,
    baseCost: 250,
    productionRate: {
      cropsPerMin: 4
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2.3
    },
    maintenanceCostPerHour: 4,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.6,
      wearRateMultiplier: 2.8
    },
    description: "Maintains optimal soil moisture. Tier 2 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 20,
        costFormula: "base_cost * (1.375 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 20,
        costFormula: "base_cost * (1.320 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 20,
        costFormula: "base_cost * (1.265 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "mineral_infuser",
      "high_pressure_nozzle"
    ],
    cosmeticSkins: [
      "skin_waterer_neon"
    ]
  },
  {
    id: "mach_harv_3_00",
    name: "Gather-Matic v3.0",
    category: "harvester",
    tier: 3,
    baseCost: 2900,
    productionRate: {
      cropsPerMin: 12
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 3
    },
    maintenanceCostPerHour: 50,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.9,
      wearRateMultiplier: 3.4
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "giga_scythe",
      "auto_sorter"
    ],
    cosmeticSkins: [
      "skin_harvester_gold"
    ]
  },
  {
    id: "mach_harv_3_01",
    name: "Scythe-Sync v3.0",
    category: "harvester",
    tier: 3,
    baseCost: 4300,
    productionRate: {
      cropsPerMin: 11
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.4,
      level_10: 2.2
    },
    maintenanceCostPerHour: 73,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.7,
      wearRateMultiplier: 2.8
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "giga_scythe",
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_gold",
      "skin_harvester_neon",
      "skin_harvester_steampunk"
    ]
  },
  {
    id: "mach_harv_3_02",
    name: "Crop-Tron Pro",
    category: "harvester",
    tier: 3,
    baseCost: 2100,
    productionRate: {
      cropsPerMin: 13
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.9
    },
    maintenanceCostPerHour: 30,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.8,
      wearRateMultiplier: 2.6
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_gold",
      "skin_harvester_neon"
    ]
  },
  {
    id: "mach_harv_3_03",
    name: "Yield-Bot v3.0",
    category: "harvester",
    tier: 3,
    baseCost: 5000,
    productionRate: {
      cropsPerMin: 11
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.2
    },
    maintenanceCostPerHour: 143,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 2,
      wearRateMultiplier: 2.6
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "auto_sorter",
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_steampunk",
      "skin_harvester_holo",
      "skin_harvester_neon"
    ]
  },
  {
    id: "mach_harv_3_04",
    name: "Crop-Bot Mk 3",
    category: "harvester",
    tier: 3,
    baseCost: 4900,
    productionRate: {
      cropsPerMin: 10
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2
    },
    maintenanceCostPerHour: 126,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.5,
      wearRateMultiplier: 2.1
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "payload_compactor",
      "giga_scythe"
    ],
    cosmeticSkins: [
      "skin_harvester_gold"
    ]
  },
  {
    id: "mach_harv_3_05",
    name: "Gather-Core Mk 3",
    category: "harvester",
    tier: 3,
    baseCost: 2400,
    productionRate: {
      cropsPerMin: 10
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 2.5
    },
    maintenanceCostPerHour: 37,
    overclockable: false,
    description: "Harvests mature crops efficiently. Tier 3 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "payload_compactor",
      "auto_sorter"
    ],
    cosmeticSkins: [
      "skin_harvester_rusty"
    ]
  },
  {
    id: "mach_harv_3_06",
    name: "Crop-Bot Pro",
    category: "harvester",
    tier: 3,
    baseCost: 700,
    productionRate: {
      cropsPerMin: 10
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.6
    },
    maintenanceCostPerHour: 16,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.5,
      wearRateMultiplier: 2.7
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "auto_sorter",
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_rusty",
      "skin_harvester_gold"
    ]
  },
  {
    id: "mach_harv_3_07",
    name: "Crop-Bot X3",
    category: "harvester",
    tier: 3,
    baseCost: 2500,
    productionRate: {
      cropsPerMin: 10
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 2.7
    },
    maintenanceCostPerHour: 55,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.9,
      wearRateMultiplier: 2.5
    },
    description: "Harvests mature crops efficiently. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_neon"
    ]
  },
  {
    id: "mach_harv_3_08",
    name: "Yield-Matic 300",
    category: "harvester",
    tier: 3,
    baseCost: 1600,
    productionRate: {
      cropsPerMin: 13
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 3
    },
    maintenanceCostPerHour: 39,
    overclockable: false,
    description: "Harvests mature crops efficiently. Tier 3 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "auto_sorter",
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_neon",
      "skin_harvester_holo",
      "skin_harvester_gold"
    ]
  },
  {
    id: "mach_harv_3_09",
    name: "Yield-Tech v3.0",
    category: "harvester",
    tier: 3,
    baseCost: 2600,
    productionRate: {
      cropsPerMin: 9
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.3
    },
    maintenanceCostPerHour: 68,
    overclockable: false,
    description: "Harvests mature crops efficiently. Tier 3 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "giga_scythe",
      "payload_compactor"
    ],
    cosmeticSkins: [
      "skin_harvester_holo"
    ]
  },
  {
    id: "mach_proc_3_00",
    name: "Mill-Forge v3.0",
    category: "processor",
    tier: 3,
    baseCost: 4300,
    productionRate: {
      cropsPerMin: 12
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.4
    },
    maintenanceCostPerHour: 109,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.6,
      wearRateMultiplier: 2.3
    },
    description: "Converts raw crops into high-value goods. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "heat_sink"
    ],
    cosmeticSkins: [
      "skin_processor_neon"
    ]
  },
  {
    id: "mach_proc_3_01",
    name: "Synth-Tech 300",
    category: "processor",
    tier: 3,
    baseCost: 2300,
    productionRate: {
      cropsPerMin: 12
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.4,
      level_10: 2.1
    },
    maintenanceCostPerHour: 37,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.3,
      wearRateMultiplier: 1.8
    },
    description: "Converts raw crops into high-value goods. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "purity_filter",
      "overclock_chip"
    ],
    cosmeticSkins: [
      "skin_processor_gold"
    ]
  },
  {
    id: "mach_proc_3_02",
    name: "Mill-Tron X3",
    category: "processor",
    tier: 3,
    baseCost: 4800,
    productionRate: {
      cropsPerMin: 12
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 2.4
    },
    maintenanceCostPerHour: 113,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.5,
      wearRateMultiplier: 2.6
    },
    description: "Converts raw crops into high-value goods. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "purity_filter"
    ],
    cosmeticSkins: [
      "skin_processor_steampunk"
    ]
  },
  {
    id: "mach_proc_3_03",
    name: "Mill-Bot Pro",
    category: "processor",
    tier: 3,
    baseCost: 4100,
    productionRate: {
      cropsPerMin: 11
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.5
    },
    maintenanceCostPerHour: 60,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.6,
      wearRateMultiplier: 2.4
    },
    description: "Converts raw crops into high-value goods. Tier 3 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "heat_sink",
      "purity_filter"
    ],
    cosmeticSkins: [
      "skin_processor_holo",
      "skin_processor_steampunk",
      "skin_processor_rusty"
    ]
  },
  {
    id: "mach_proc_3_04",
    name: "Refine-Sync Pro",
    category: "processor",
    tier: 3,
    baseCost: 1100,
    productionRate: {
      cropsPerMin: 10
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.1
    },
    maintenanceCostPerHour: 24,
    overclockable: false,
    description: "Converts raw crops into high-value goods. Tier 3 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 25,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 25,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 25,
        costFormula: "base_cost * (1.322 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 2,
    compatibleModules: [
      "overclock_chip"
    ],
    cosmeticSkins: [
      "skin_processor_gold",
      "skin_processor_holo"
    ]
  },
  {
    id: "mach_proc_4_05",
    name: "Refine-Core 4000",
    category: "processor",
    tier: 4,
    baseCost: 19000,
    productionRate: {
      cropsPerMin: 23
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2.2
    },
    maintenanceCostPerHour: 367,
    overclockable: false,
    description: "Converts raw crops into high-value goods. Tier 4 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "overclock_chip",
      "heat_sink",
      "purity_filter"
    ],
    cosmeticSkins: [
      "skin_processor_steampunk"
    ]
  },
  {
    id: "mach_proc_4_06",
    name: "Mill-Sync Pro",
    category: "processor",
    tier: 4,
    baseCost: 31000,
    productionRate: {
      cropsPerMin: 22
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.8
    },
    maintenanceCostPerHour: 685,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.9,
      wearRateMultiplier: 2.3
    },
    description: "Converts raw crops into high-value goods. Tier 4 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "purity_filter",
      "heat_sink"
    ],
    cosmeticSkins: [
      "skin_processor_holo"
    ]
  },
  {
    id: "mach_proc_4_07",
    name: "Refine-Max v4.0",
    category: "processor",
    tier: 4,
    baseCost: 21000,
    productionRate: {
      cropsPerMin: 20
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 3.1
    },
    maintenanceCostPerHour: 447,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.7,
      wearRateMultiplier: 2.8
    },
    description: "Converts raw crops into high-value goods. Tier 4 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "overclock_chip",
      "purity_filter"
    ],
    cosmeticSkins: [
      "skin_processor_holo"
    ]
  },
  {
    id: "mach_proc_4_08",
    name: "Blend-Tech X4",
    category: "processor",
    tier: 4,
    baseCost: 5800,
    productionRate: {
      cropsPerMin: 25
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 2,
      level_10: 2.7
    },
    maintenanceCostPerHour: 157,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.4,
      wearRateMultiplier: 2.2
    },
    description: "Converts raw crops into high-value goods. Tier 4 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "overclock_chip",
      "purity_filter"
    ],
    cosmeticSkins: [
      "skin_processor_neon",
      "skin_processor_steampunk"
    ]
  },
  {
    id: "mach_proc_4_09",
    name: "Synth-Tron Pro",
    category: "processor",
    tier: 4,
    baseCost: 41000,
    productionRate: {
      cropsPerMin: 22
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 2,
      level_10: 3.2
    },
    maintenanceCostPerHour: 632,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.9,
      wearRateMultiplier: 2.8
    },
    description: "Converts raw crops into high-value goods. Tier 4 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "purity_filter",
      "overclock_chip"
    ],
    cosmeticSkins: [
      "skin_processor_steampunk",
      "skin_processor_rusty"
    ]
  },
  {
    id: "mach_dron_4_00",
    name: "Aero-Sync Mk 4",
    category: "drone",
    tier: 4,
    baseCost: 32000,
    productionRate: {
      cropsPerMin: 9
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.9,
      level_10: 3.2
    },
    maintenanceCostPerHour: 612,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.9,
      wearRateMultiplier: 3.3
    },
    description: "Autonomous aerial farm maintenance. Tier 4 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "ai_pathfinder",
      "aero_battery",
      "cargo_net"
    ],
    cosmeticSkins: [
      "skin_drone_holo",
      "skin_drone_rusty",
      "skin_drone_steampunk"
    ]
  },
  {
    id: "mach_dron_4_01",
    name: "Swift-Tech 4000",
    category: "drone",
    tier: 4,
    baseCost: 11000,
    productionRate: {
      cropsPerMin: 10
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2
    },
    maintenanceCostPerHour: 265,
    overclockable: false,
    description: "Autonomous aerial farm maintenance. Tier 4 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "ai_pathfinder",
      "cargo_net",
      "aero_battery"
    ],
    cosmeticSkins: [
      "skin_drone_holo"
    ]
  },
  {
    id: "mach_dron_4_02",
    name: "Opti-Matic 4000",
    category: "drone",
    tier: 4,
    baseCost: 43000,
    productionRate: {
      cropsPerMin: 9
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.9,
      level_10: 2.6
    },
    maintenanceCostPerHour: 657,
    overclockable: false,
    description: "Autonomous aerial farm maintenance. Tier 4 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "cargo_net",
      "aero_battery"
    ],
    cosmeticSkins: [
      "skin_drone_steampunk",
      "skin_drone_neon"
    ]
  },
  {
    id: "mach_dron_4_03",
    name: "Sky-Sync X4",
    category: "drone",
    tier: 4,
    baseCost: 41000,
    productionRate: {
      cropsPerMin: 12
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.6,
      level_10: 2.4
    },
    maintenanceCostPerHour: 529,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.3,
      wearRateMultiplier: 2.1
    },
    description: "Autonomous aerial farm maintenance. Tier 4 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "ai_pathfinder",
      "cargo_net",
      "aero_battery"
    ],
    cosmeticSkins: [
      "skin_drone_rusty",
      "skin_drone_gold"
    ]
  },
  {
    id: "mach_dron_4_04",
    name: "Sky-Tech v4.0",
    category: "drone",
    tier: 4,
    baseCost: 20000,
    productionRate: {
      cropsPerMin: 14
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 2.5
    },
    maintenanceCostPerHour: 566,
    overclockable: false,
    description: "Autonomous aerial farm maintenance. Tier 4 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 30,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 30,
        costFormula: "base_cost * (1.440 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 30,
        costFormula: "base_cost * (1.380 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "aero_battery",
      "ai_pathfinder"
    ],
    cosmeticSkins: [
      "skin_drone_steampunk"
    ]
  },
  {
    id: "mach_dron_5_05",
    name: "Aero-Sync 5000",
    category: "drone",
    tier: 5,
    baseCost: 100000,
    productionRate: {
      cropsPerMin: 28
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.4,
      level_10: 2.2
    },
    maintenanceCostPerHour: 1778,
    overclockable: false,
    description: "Autonomous aerial farm maintenance. Tier 5 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 35,
        costFormula: "base_cost * (1.563 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 35,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 35,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "aero_battery",
      "cargo_net",
      "ai_pathfinder"
    ],
    cosmeticSkins: [
      "skin_drone_holo",
      "skin_drone_neon"
    ]
  },
  {
    id: "mach_dron_5_06",
    name: "Sky-Tron 500",
    category: "drone",
    tier: 5,
    baseCost: 200000,
    productionRate: {
      cropsPerMin: 29
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.3
    },
    maintenanceCostPerHour: 5040,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 2,
      wearRateMultiplier: 3.4
    },
    description: "Autonomous aerial farm maintenance. Tier 5 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 35,
        costFormula: "base_cost * (1.563 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 35,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 35,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "aero_battery",
      "ai_pathfinder"
    ],
    cosmeticSkins: [
      "skin_drone_gold",
      "skin_drone_steampunk",
      "skin_drone_holo"
    ]
  },
  {
    id: "mach_dron_5_07",
    name: "Sky-Tron Mk 5",
    category: "drone",
    tier: 5,
    baseCost: 330000,
    productionRate: {
      cropsPerMin: 23
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.5,
      level_10: 2.5
    },
    maintenanceCostPerHour: 7237,
    overclockable: false,
    description: "Autonomous aerial farm maintenance. Tier 5 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 35,
        costFormula: "base_cost * (1.563 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 35,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 35,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "cargo_net"
    ],
    cosmeticSkins: [
      "skin_drone_rusty",
      "skin_drone_steampunk"
    ]
  },
  {
    id: "mach_dron_5_08",
    name: "Aero-Forge Pro",
    category: "drone",
    tier: 5,
    baseCost: 360000,
    productionRate: {
      cropsPerMin: 28
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.8,
      level_10: 2.6
    },
    maintenanceCostPerHour: 4296,
    overclockable: true,
    overclockEffects: {
      speedMultiplier: 1.5,
      wearRateMultiplier: 2.2
    },
    description: "Autonomous aerial farm maintenance. Tier 5 technology. Supports dangerous overclocking.",
    upgrades: [
      {
        branch: "speed",
        levels: 35,
        costFormula: "base_cost * (1.563 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 35,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 35,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "cargo_net",
      "aero_battery",
      "ai_pathfinder"
    ],
    cosmeticSkins: [
      "skin_drone_neon",
      "skin_drone_holo"
    ]
  },
  {
    id: "mach_dron_5_09",
    name: "Swift-Max v5.0",
    category: "drone",
    tier: 5,
    baseCost: 460000,
    productionRate: {
      cropsPerMin: 28
    },
    efficiencyCurve: {
      level_1: 1,
      level_5: 1.7,
      level_10: 2.6
    },
    maintenanceCostPerHour: 5319,
    overclockable: false,
    description: "Autonomous aerial farm maintenance. Tier 5 technology. Stable design, cannot be overclocked.",
    upgrades: [
      {
        branch: "speed",
        levels: 35,
        costFormula: "base_cost * (1.563 ^ level)",
        effectPerLevel: "+{val}% Production Speed",
        maxEffectVal: 100
      },
      {
        branch: "yield",
        levels: 35,
        costFormula: "base_cost * (1.500 ^ level)",
        effectPerLevel: "+{val}% Output Yield",
        maxEffectVal: 50
      },
      {
        branch: "durability",
        levels: 35,
        costFormula: "base_cost * (1.438 ^ level)",
        effectPerLevel: "-{val}% Wear Rate",
        maxEffectVal: 75
      }
    ],
    moduleSlots: 3,
    compatibleModules: [
      "cargo_net",
      "ai_pathfinder"
    ],
    cosmeticSkins: [
      "skin_drone_neon",
      "skin_drone_gold",
      "skin_drone_holo"
    ]
  }
];

export const getAugmentedMachine = (id: string): AugmentedMachineDef | undefined => AUGMENTED_MACHINES.find(m => m.id === id);
