// Auto-generated by economy/generate_content.ts
import narrativeData from '../data_exports/narrative_content.json';

export const NPCs = narrativeData.npcs;
export const SEASONAL_EVENTS = narrativeData.seasonal_events;
export const ACHIEVEMENTS = narrativeData.achievements;
export const MICROCOPY = narrativeData.microcopy as Record<string, string>;

export const t = (key: string, variables?: Record<string, string | number>): string => {
  let text = MICROCOPY[key] || key;
  if (variables) {
    for (const [k, v] of Object.entries(variables)) {
      text = text.replace(`{${k}}`, String(v));
    }
  }
  return text;
};
