// Auto-generated by economy/generate_progression.ts
export interface UnlockGate {
  tier: number;
  type: 'crop' | 'machine' | 'region';
  name: string;
  requirementDesc: string;
  coinsThreshold: number;
}

export const UNLOCKS: UnlockGate[] = [
  {
    tier: 1,
    type: "machine",
    name: "Root-Bot Mk 1",
    requirementDesc: "earn 50 coins",
    coinsThreshold: 50
  },
  {
    tier: 1,
    type: "machine",
    name: "Terra-Core 100",
    requirementDesc: "earn 60 coins",
    coinsThreshold: 60
  },
  {
    tier: 1,
    type: "machine",
    name: "Furrow-Matic 100",
    requirementDesc: "earn 70 coins",
    coinsThreshold: 70
  },
  {
    tier: 1,
    type: "machine",
    name: "Root-Tech v1.0",
    requirementDesc: "earn 80 coins",
    coinsThreshold: 80
  },
  {
    tier: 1,
    type: "machine",
    name: "Soil-Bot v1.0",
    requirementDesc: "earn 90 coins",
    coinsThreshold: 90
  },
  {
    tier: 1,
    type: "machine",
    name: "Seed-Max 1000",
    requirementDesc: "earn 100 coins",
    coinsThreshold: 100
  },
  {
    tier: 1,
    type: "machine",
    name: "Seed-Matic 1000",
    requirementDesc: "earn 110 coins",
    coinsThreshold: 110
  },
  {
    tier: 1,
    type: "machine",
    name: "Seed-Forge Mk 1",
    requirementDesc: "earn 120 coins",
    coinsThreshold: 120
  },
  {
    tier: 1,
    type: "machine",
    name: "Soil-Tron v1.0",
    requirementDesc: "earn 130 coins",
    coinsThreshold: 130
  },
  {
    tier: 1,
    type: "machine",
    name: "Terra-Tron 100",
    requirementDesc: "earn 140 coins",
    coinsThreshold: 140
  },
  {
    tier: 2,
    type: "machine",
    name: "Mist-Forge 2000",
    requirementDesc: "earn 150 coins",
    coinsThreshold: 150
  },
  {
    tier: 2,
    type: "machine",
    name: "Flow-Matic 200",
    requirementDesc: "earn 160 coins",
    coinsThreshold: 160
  },
  {
    tier: 2,
    type: "machine",
    name: "Aqua-Sync 2000",
    requirementDesc: "earn 170 coins",
    coinsThreshold: 170
  },
  {
    tier: 2,
    type: "machine",
    name: "Irrig-Sync v2.0",
    requirementDesc: "earn 180 coins",
    coinsThreshold: 180
  },
  {
    tier: 2,
    type: "machine",
    name: "Hydro-Core Pro",
    requirementDesc: "earn 190 coins",
    coinsThreshold: 190
  },
  {
    tier: 2,
    type: "machine",
    name: "Irrig-Max Mk 2",
    requirementDesc: "earn 200 coins",
    coinsThreshold: 200
  },
  {
    tier: 2,
    type: "machine",
    name: "Irrig-Tron X2",
    requirementDesc: "earn 210 coins",
    coinsThreshold: 210
  },
  {
    tier: 2,
    type: "crop",
    name: "Mint",
    requirementDesc: "earn 220 coins",
    coinsThreshold: 220
  },
  {
    tier: 2,
    type: "machine",
    name: "Irrig-Max Pro",
    requirementDesc: "earn 230 coins",
    coinsThreshold: 230
  },
  {
    tier: 2,
    type: "crop",
    name: "Kale",
    requirementDesc: "earn 240 coins",
    coinsThreshold: 240
  },
  {
    tier: 2,
    type: "machine",
    name: "Flow-Matic 2000",
    requirementDesc: "earn 250 coins",
    coinsThreshold: 250
  },
  {
    tier: 2,
    type: "machine",
    name: "Aqua-Max X2",
    requirementDesc: "earn 260 coins",
    coinsThreshold: 260
  },
  {
    tier: 2,
    type: "crop",
    name: "Basil",
    requirementDesc: "earn 270 coins",
    coinsThreshold: 270
  },
  {
    tier: 2,
    type: "crop",
    name: "Soybean",
    requirementDesc: "earn 280 coins",
    coinsThreshold: 280
  },
  {
    tier: 2,
    type: "crop",
    name: "Lentil",
    requirementDesc: "earn 290 coins",
    coinsThreshold: 290
  },
  {
    tier: 2,
    type: "crop",
    name: "Onion",
    requirementDesc: "earn 300 coins",
    coinsThreshold: 300
  },
  {
    tier: 2,
    type: "crop",
    name: "Rice",
    requirementDesc: "earn 310 coins",
    coinsThreshold: 310
  },
  {
    tier: 1,
    type: "crop",
    name: "Garlic",
    requirementDesc: "earn 320 coins",
    coinsThreshold: 320
  },
  {
    tier: 2,
    type: "crop",
    name: "Sunflower",
    requirementDesc: "earn 330 coins",
    coinsThreshold: 330
  },
  {
    tier: 3,
    type: "machine",
    name: "Crop-Bot Pro",
    requirementDesc: "earn 340 coins",
    coinsThreshold: 340
  },
  {
    tier: 2,
    type: "crop",
    name: "Chamomile",
    requirementDesc: "earn 350 coins",
    coinsThreshold: 350
  },
  {
    tier: 2,
    type: "crop",
    name: "Oats",
    requirementDesc: "earn 360 coins",
    coinsThreshold: 360
  },
  {
    tier: 2,
    type: "crop",
    name: "Pumpkin",
    requirementDesc: "earn 370 coins",
    coinsThreshold: 370
  },
  {
    tier: 2,
    type: "crop",
    name: "Fennel",
    requirementDesc: "earn 380 coins",
    coinsThreshold: 380
  },
  {
    tier: 2,
    type: "crop",
    name: "Sugarcane",
    requirementDesc: "earn 390 coins",
    coinsThreshold: 390
  },
  {
    tier: 2,
    type: "crop",
    name: "Pepper",
    requirementDesc: "earn 400 coins",
    coinsThreshold: 400
  },
  {
    tier: 2,
    type: "crop",
    name: "Barley",
    requirementDesc: "earn 410 coins",
    coinsThreshold: 410
  },
  {
    tier: 2,
    type: "crop",
    name: "Buckwheat",
    requirementDesc: "earn 420 coins",
    coinsThreshold: 420
  },
  {
    tier: 3,
    type: "machine",
    name: "Refine-Sync Pro",
    requirementDesc: "earn 430 coins",
    coinsThreshold: 430
  },
  {
    tier: 2,
    type: "crop",
    name: "Ginger",
    requirementDesc: "earn 440 coins",
    coinsThreshold: 440
  },
  {
    tier: 3,
    type: "machine",
    name: "Yield-Matic 300",
    requirementDesc: "earn 560 coins",
    coinsThreshold: 560
  },
  {
    tier: 2,
    type: "crop",
    name: "Lavender",
    requirementDesc: "earn 613 coins",
    coinsThreshold: 613
  },
  {
    tier: 3,
    type: "machine",
    name: "Crop-Tron Pro",
    requirementDesc: "earn 735 coins",
    coinsThreshold: 735
  },
  {
    tier: 3,
    type: "machine",
    name: "Synth-Tech 300",
    requirementDesc: "earn 805 coins",
    coinsThreshold: 805
  },
  {
    tier: 3,
    type: "machine",
    name: "Gather-Core Mk 3",
    requirementDesc: "earn 840 coins",
    coinsThreshold: 840
  },
  {
    tier: 3,
    type: "machine",
    name: "Crop-Bot X3",
    requirementDesc: "earn 875 coins",
    coinsThreshold: 875
  },
  {
    tier: 3,
    type: "crop",
    name: "Grape",
    requirementDesc: "earn 888 coins",
    coinsThreshold: 888
  },
  {
    tier: 3,
    type: "machine",
    name: "Yield-Tech v3.0",
    requirementDesc: "earn 910 coins",
    coinsThreshold: 910
  },
  {
    tier: 3,
    type: "crop",
    name: "Strawberry",
    requirementDesc: "earn 1,013 coins",
    coinsThreshold: 1013
  },
  {
    tier: 3,
    type: "machine",
    name: "Gather-Matic v3.0",
    requirementDesc: "earn 1,015 coins",
    coinsThreshold: 1015
  },
  {
    tier: 3,
    type: "crop",
    name: "Mango",
    requirementDesc: "earn 1,200 coins",
    coinsThreshold: 1200
  },
  {
    tier: 3,
    type: "crop",
    name: "Blueberry",
    requirementDesc: "earn 1,300 coins",
    coinsThreshold: 1300
  },
  {
    tier: 3,
    type: "crop",
    name: "Tea",
    requirementDesc: "earn 1,350 coins",
    coinsThreshold: 1350
  },
  {
    tier: 3,
    type: "crop",
    name: "Papaya",
    requirementDesc: "earn 1,400 coins",
    coinsThreshold: 1400
  },
  {
    tier: 3,
    type: "machine",
    name: "Mill-Bot Pro",
    requirementDesc: "earn 1,435 coins",
    coinsThreshold: 1435
  },
  {
    tier: 3,
    type: "machine",
    name: "Scythe-Sync v3.0",
    requirementDesc: "earn 1,505 coins",
    coinsThreshold: 1505
  },
  {
    tier: 3,
    type: "machine",
    name: "Mill-Forge v3.0",
    requirementDesc: "earn 1,515 coins",
    coinsThreshold: 1515
  },
  {
    tier: 3,
    type: "machine",
    name: "Mill-Tron X3",
    requirementDesc: "earn 1,680 coins",
    coinsThreshold: 1680
  },
  {
    tier: 3,
    type: "machine",
    name: "Crop-Bot Mk 3",
    requirementDesc: "earn 1,715 coins",
    coinsThreshold: 1715
  },
  {
    tier: 3,
    type: "machine",
    name: "Yield-Bot v3.0",
    requirementDesc: "earn 1,750 coins",
    coinsThreshold: 1750
  },
  {
    tier: 3,
    type: "crop",
    name: "Pineapple",
    requirementDesc: "earn 2,000 coins",
    coinsThreshold: 2000
  },
  {
    tier: 4,
    type: "machine",
    name: "Blend-Tech X4",
    requirementDesc: "earn 2,030 coins",
    coinsThreshold: 2030
  },
  {
    tier: 3,
    type: "crop",
    name: "Coffee",
    requirementDesc: "earn 2,125 coins",
    coinsThreshold: 2125
  },
  {
    tier: 3,
    type: "crop",
    name: "Cacao",
    requirementDesc: "earn 2,438 coins",
    coinsThreshold: 2438
  },
  {
    tier: 4,
    type: "crop",
    name: "Chia",
    requirementDesc: "earn 3,325 coins",
    coinsThreshold: 3325
  },
  {
    tier: 4,
    type: "machine",
    name: "Swift-Tech 4000",
    requirementDesc: "earn 3,850 coins",
    coinsThreshold: 3850
  },
  {
    tier: 3,
    type: "crop",
    name: "Vanilla",
    requirementDesc: "earn 4,125 coins",
    coinsThreshold: 4125
  },
  {
    tier: 4,
    type: "crop",
    name: "Quinoa",
    requirementDesc: "earn 4,700 coins",
    coinsThreshold: 4700
  },
  {
    tier: 4,
    type: "crop",
    name: "Tahitian Lime",
    requirementDesc: "earn 6,125 coins",
    coinsThreshold: 6125
  },
  {
    tier: 4,
    type: "machine",
    name: "Refine-Core 4000",
    requirementDesc: "earn 6,650 coins",
    coinsThreshold: 6650
  },
  {
    tier: 4,
    type: "crop",
    name: "Avocado",
    requirementDesc: "earn 6,700 coins",
    coinsThreshold: 6700
  },
  {
    tier: 4,
    type: "machine",
    name: "Sky-Tech v4.0",
    requirementDesc: "earn 7,000 coins",
    coinsThreshold: 7000
  },
  {
    tier: 4,
    type: "crop",
    name: "Dragon Fruit",
    requirementDesc: "earn 7,125 coins",
    coinsThreshold: 7125
  },
  {
    tier: 4,
    type: "machine",
    name: "Refine-Max v4.0",
    requirementDesc: "earn 7,350 coins",
    coinsThreshold: 7350
  },
  {
    tier: 4,
    type: "crop",
    name: "Blue Oyster Mushroom",
    requirementDesc: "earn 8,163 coins",
    coinsThreshold: 8163
  },
  {
    tier: 4,
    type: "crop",
    name: "Artichoke",
    requirementDesc: "earn 8,750 coins",
    coinsThreshold: 8750
  },
  {
    tier: 4,
    type: "machine",
    name: "Mill-Sync Pro",
    requirementDesc: "earn 10,850 coins",
    coinsThreshold: 10850
  },
  {
    tier: 4,
    type: "machine",
    name: "Aero-Sync Mk 4",
    requirementDesc: "earn 11,200 coins",
    coinsThreshold: 11200
  },
  {
    tier: 4,
    type: "crop",
    name: "Black Truffle",
    requirementDesc: "earn 11,325 coins",
    coinsThreshold: 11325
  },
  {
    tier: 4,
    type: "crop",
    name: "Saffron",
    requirementDesc: "earn 11,750 coins",
    coinsThreshold: 11750
  },
  {
    tier: 4,
    type: "machine",
    name: "Synth-Tron Pro",
    requirementDesc: "earn 14,350 coins",
    coinsThreshold: 14350
  },
  {
    tier: 4,
    type: "machine",
    name: "Sky-Sync X4",
    requirementDesc: "earn 14,360 coins",
    coinsThreshold: 14360
  },
  {
    tier: 4,
    type: "machine",
    name: "Opti-Matic 4000",
    requirementDesc: "earn 15,050 coins",
    coinsThreshold: 15050
  },
  {
    tier: 4,
    type: "crop",
    name: "Wasabi Root",
    requirementDesc: "earn 19,950 coins",
    coinsThreshold: 19950
  },
  {
    tier: 5,
    type: "machine",
    name: "Aero-Sync 5000",
    requirementDesc: "earn 35,000 coins",
    coinsThreshold: 35000
  },
  {
    tier: 2,
    type: "region",
    name: "Riverlands",
    requirementDesc: "earn 50,000 coins",
    coinsThreshold: 50000
  },
  {
    tier: 5,
    type: "machine",
    name: "Sky-Tron 500",
    requirementDesc: "earn 70,000 coins",
    coinsThreshold: 70000
  },
  {
    tier: 5,
    type: "crop",
    name: "Ghost Pepper",
    requirementDesc: "earn 1,06,338 coins",
    coinsThreshold: 106338
  },
  {
    tier: 5,
    type: "machine",
    name: "Sky-Tron Mk 5",
    requirementDesc: "earn 1,15,500 coins",
    coinsThreshold: 115500
  },
  {
    tier: 5,
    type: "crop",
    name: "Argan Blossom",
    requirementDesc: "earn 1,22,163 coins",
    coinsThreshold: 122163
  },
  {
    tier: 5,
    type: "machine",
    name: "Aero-Forge Pro",
    requirementDesc: "earn 1,26,000 coins",
    coinsThreshold: 126000
  },
  {
    tier: 5,
    type: "crop",
    name: "Kopi Luwak",
    requirementDesc: "earn 1,37,750 coins",
    coinsThreshold: 137750
  },
  {
    tier: 5,
    type: "crop",
    name: "Sea Grape",
    requirementDesc: "earn 1,53,163 coins",
    coinsThreshold: 153163
  },
  {
    tier: 5,
    type: "machine",
    name: "Swift-Max v5.0",
    requirementDesc: "earn 1,61,000 coins",
    coinsThreshold: 161000
  },
  {
    tier: 5,
    type: "crop",
    name: "Manuka Flower",
    requirementDesc: "earn 1,68,400 coins",
    coinsThreshold: 168400
  },
  {
    tier: 5,
    type: "crop",
    name: "White Truffle",
    requirementDesc: "earn 1,98,425 coins",
    coinsThreshold: 198425
  },
  {
    tier: 5,
    type: "crop",
    name: "Matsutake",
    requirementDesc: "earn 2,27,950 coins",
    coinsThreshold: 227950
  },
  {
    tier: 3,
    type: "region",
    name: "Desert Oasis",
    requirementDesc: "earn 2,50,000 coins",
    coinsThreshold: 250000
  },
  {
    tier: 5,
    type: "crop",
    name: "Oud Resin",
    requirementDesc: "earn 2,85,800 coins",
    coinsThreshold: 285800
  },
  {
    tier: 5,
    type: "crop",
    name: "Aurora Cacao",
    requirementDesc: "earn 3,37,700 coins",
    coinsThreshold: 337700
  },
  {
    tier: 5,
    type: "crop",
    name: "Lunar Melon",
    requirementDesc: "earn 3,61,000 coins",
    coinsThreshold: 361000
  },
  {
    tier: 4,
    type: "region",
    name: "Frozen Tundra",
    requirementDesc: "earn 10,00,000 coins",
    coinsThreshold: 1000000
  },
  {
    tier: 5,
    type: "region",
    name: "Volcanic Soil",
    requirementDesc: "earn 50,00,000 coins",
    coinsThreshold: 5000000
  },
  {
    tier: 6,
    type: "region",
    name: "Sky Farmlands",
    requirementDesc: "earn 2,50,00,000 coins",
    coinsThreshold: 25000000
  }
];

export const PRESTIGE_DIVISOR = 8000000;
export const getNextUnlock = (currentCoins: number): UnlockGate | undefined => {
  return UNLOCKS.find(u => u.coinsThreshold > currentCoins);
};
