// Auto-generated by economy/generate_workers_regions.ts
import workersData from '../data_exports/workers.json';
import regionsData from '../data_exports/regions.json';

export interface WorkerDef {
  id: string;
  name: string;
  role: string;
  tier: string;
  hire_cost: number;
  efficiency_bonus: number;
  description: string;
}

export interface RegionDef {
  id: string;
  name: string;
  unlock_cost: number;
  multiplier: number;
  weather_affinity: string;
  description: string;
  available_slots: number;
}

export const WORKERS: WorkerDef[] = workersData as WorkerDef[];
export const REGIONS: RegionDef[] = regionsData as RegionDef[];

export const getWorker = (id: string) => WORKERS.find(w => w.id === id);
export const getRegion = (id: string) => REGIONS.find(r => r.id === id);
